package Enum;

public enum Commands {
    HELP,EXIT,BOUNDS,SAVE, LOAD, SERVICE, EATING,LODGING,LEISURE,SERVICES,STUDENT,LEAVE,STUDENTS,GO,MOVE,USERS, WHERE,VISITED, UNKNOWN, STAR, RANKING,RANKED, FIND, TAG

}
